Repository markshust/docker-magento, pull requests merged in 2025-03, with the labels that each got.

#1300 Fix bin/setup-ssl doesn't work for multiple domains #1257
  compose/bin/setup-ssl
Labels: size:XS

#830 Add SSL CA integration support for Firefox Developer Edition
  compose/bin/setup-ssl-ca
Labels: needs confirmation, size:XS

#1305 New PHP version deps
  .github/workflows/build-php-8-1.yml
  .github/workflows/build-php-8-2.yml
  .github/workflows/build-php-8-3.yml
  .github/workflows/build-php-8-4.yml
  images/php/8.1/Dockerfile
  images/php/8.2/Dockerfile
  images/php/8.3/Dockerfile
  images/php/8.4/Dockerfile
Labels: dependencies, size:L

#956 bin/docker-start helper script
  README.md
  compose/Makefile
  compose/bin/docker-start
Labels: help wanted, size:XS

#913 Move selenium service & configuration to compose.dev.yaml
  compose/compose.dev.yaml
  compose/compose.yaml
Labels: size:S

#1308 Re-categorized accessing backend docs under Misc, removed old message…
  README.md
Labels: size:M

#1309 Fix cron unexpectedly fails to start after being enabled #760
  compose/bin/cron
  compose/bin/start
Labels: size:XS
