Repository markshust/docker-magento, pull requests merged in 2025-04, with the labels that each got.

#1315 51.0.0 (Magento 2.4.8 support)
  .github/workflows/build-nginx-1-24.yml
  .github/workflows/build-php-8-1.yml
  .github/workflows/build-php-8-2.yml
  .github/workflows/build-php-8-3.yml
  .github/workflows/build-php-8-4.yml
  CHANGELOG.md
  README.md
  compose/Makefile
  compose/bin/cron
  compose/bin/docker-start
  compose/bin/setup-ssl
  compose/bin/start
  compose/compose.yaml
  compose/env/elasticsearch.env
  compose/env/opensearch.env
  images/nginx/1.24/Dockerfile
  images/nginx/1.24/conf/nginx.conf
  images/php/8.1/Dockerfile
  images/php/8.2/Dockerfile
  images/php/8.3/Dockerfile
  images/php/8.4/Dockerfile
Labels: documentation, size:L

#1321 Update README.md
  README.md
Labels: documentation, size:S, lgtm

#1326 Add RabbitMQ 4 image for Magento 2.4.8 support #1319 (drop support for 3.8)
  .github/workflows/build-rabbitmq-4-1.yml
  README.md
  compose/compose.yaml
  images/rabbitmq/4.1/Dockerfile
  images/rabbitmq/4.1/conf/rabbitmq.conf
Labels: size:S

#1327 Add Valkey 8 image for Magento 2.4.8 support #1320
  compose/compose.yaml
Labels: size:XS

#1324 Remove commented-out optimizer flags which do not apply to MySQL
  compose/compose.yaml
Labels: size:XS

#1329 Make fully compatible with MariaDB 10.4/11.6 and MySQL 8.0/8.4
  compose/compose.healthcheck.yaml
  compose/compose.yaml
Labels: size:XS

#1330 Optimize healthchecks and make them consistent
  compose/compose.healthcheck.yaml
Labels: size:M

#1331 Feature/version bump
  .github/workflows/build-rabbitmq-4-1.yml
  CHANGELOG.md
  README.md
  compose/compose.healthcheck.yaml
  compose/compose.yaml
  images/rabbitmq/4.1/Dockerfile
  images/rabbitmq/4.1/conf/rabbitmq.conf
Labels: feature, size:L
